groupbuyorganizer/admin/routes.py
from flask import Blueprint, flash, make_response, redirect, render_template, request, url_for
from flask_login import current_user, login_required
import pdfkit

from datetime import timezone

from groupbuyorganizer import database
from groupbuyorganizer.admin.forms import ApplicationSettingsForm, CreateCategoryForm
from groupbuyorganizer.admin.models import Category, Instance, User
from groupbuyorganizer.admin.utilities import admin_protector


admin = Blueprint('admin', __name__)

@admin.route("/category_settings/", methods=['GET', 'POST'])
@login_required
def category_settings():
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    form = CreateCategoryForm()
    if form.validate_on_submit():
        category = Category(name=form.category_name.data)
        database.session.add(category)
        database.session.commit()
        flash('Category successfully added!', 'success')
        return redirect(url_for('admin.category_settings'))
    elif request.method == 'GET':
        categories = Category.query.order_by(Category.name.asc()).all()
    return render_template('category_settings.html', title='Category Settings', categories=categories, form=form)


@admin.route("/category_settings/<int:category_id>/edit/", methods=['GET', 'POST'])
@login_required
def category_edit(category_id):
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    category = Category.query.get_or_404(category_id)
    form = CreateCategoryForm()
    if form.validate_on_submit():
        category.name = form.category_name.data
        database.session.commit()
        flash(f'{category.name} has been edited!', 'info')
        return redirect(url_for('admin.category_settings'))
    elif request.method == 'GET':
        form.category_name.data = category.name
    return render_template('category_edit.html', title='Edit Category Name', form=form)


@admin.route("/categories/<int:category_id>/remove/", methods=['GET'])
@login_required
def category_remove(category_id):
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('Access denied', 'danger')
        return redirect(url_for('admin.category_settings'))

    flash_message = 'Category deleted! '
    if category.items:
        flash_message += " Item(s) in this category have been moved to 'Uncategorized.'"
        for item in category.items:
            item.category_id = 1
            database.session.commit()
    database.session.delete(category)
    database.session.commit()
    flash(f'{flash_message}', 'info')
    return redirect(url_for('admin.category_settings'))


@admin.route("/user_settings/")
@login_required
def user_settings():
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    users = User.query.order_by(User.username.asc()).all()
    for user in users: # Making the DateTime database column human readable and converted to local timezone.
        ugly_string = user.date_created.replace(tzinfo=timezone.utc).astimezone(tz=None)
        user.date_created = ugly_string.strftime("%x %X")

    return render_template('user_settings.html', title='User Settings', users=users)


@admin.route("/user_settings/<int:user_id>/promote", methods=['GET'])
@login_required
def promote_user(user_id):
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    user = User.query.get_or_404(user_id)
    admin_protector(user)
    user.is_admin = True
    database.session.commit()
    flash(f'{user.username} has been promoted to admin!', 'info')
    return redirect(url_for('admin.user_settings'))


@admin.route("/user_settings/<int:user_id>/demote")
@login_required
def demote_user(user_id):
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    user = User.query.get_or_404(user_id)
    admin_protector(user)
    user.is_admin = False
    database.session.commit()
    flash(f'{user.username} has been demoted!', 'info')
    return redirect(url_for('admin.user_settings'))


@admin.route("/user_settings/<int:user_id>/disable")
@login_required
def disable_user(user_id):
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    user = User.query.get_or_404(user_id)
    admin_protector(user)
    user.is_admin = False
    user.disabled = True
    database.session.commit()
    flash(f'{user.username} has been disabled!', 'info')
    return redirect(url_for('admin.user_settings'))


@admin.route("/user_settings/<int:user_id>/enable")
@login_required
def enable_user(user_id):
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    user = User.query.get_or_404(user_id)
    admin_protector(user)
    user.disabled = False
    database.session.commit()
    flash(f'{user.username} has been re-enabled!', 'info')
    return redirect(url_for('admin.user_settings'))


@admin.route("/app_settings", methods=['GET', 'POST'])
@login_required
def app_settings():
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    instance = Instance.query.first()
    form = ApplicationSettingsForm()
    if form.validate_on_submit():
        instance.registration_enabled = form.registration_enabled.data
        instance.users_can_see_master_overview = form.users_can_see_master_overview.data
        instance.wkhtmltopdf_path = form.wkhtmltopdf_path.data
        database.session.commit()
        flash('Changes saved!', 'info')
        return redirect(url_for('admin.app_settings'))
    elif request.method == 'GET':
        form.registration_enabled.data = instance.registration_enabled
        form.users_can_see_master_overview.data = instance.users_can_see_master_overview
        if instance.wkhtmltopdf_path is not None:
            form.wkhtmltopdf_path.data = instance.wkhtmltopdf_path
    return render_template('app_settings.html', title='Application Settings', form=form)


@admin.route("/app_settings/test_pdf/", methods=['GET'])
@login_required
def test_pdf():
    '''Once you add the absolute file path of the wkhtmltopdf binary in the app settings, this route serves as a way for
    the site admin to check that it is properly configured.
    '''
    instance = Instance.query.first()
    config = pdfkit.configuration(wkhtmltopdf=instance.wkhtmltopdf_path)
    rendered = render_template('test_pdf.html', title='PDF Output Check...')
    pdf = pdfkit.from_string(rendered, False, configuration=config, options={'quiet':''})
    response = make_response(pdf)
    response.headers['Content-Type'] = 'application/pdf'
    response.headers['Content-Disposition'] = 'inline; filename=test_pdf.pdf'
    return response

groupbuyorganizer/events/routes.py
from flask import Blueprint, flash, make_response, redirect, render_template, request, url_for
from flask_login import current_user, login_required
import pdfkit

from groupbuyorganizer import database
from groupbuyorganizer.admin.models import Category, Instance, User
from groupbuyorganizer.events.forms import CreateItemForm, CreateCaseSplitForm, CreateEventForm, CaseQuantityOrderForm,\
    EditItemForm, EventExtraChargeForm, SelectUserFromEventForm
from groupbuyorganizer.events.models import CaseBuy, CasePieceCommit, CaseSplit, Event, Item
from groupbuyorganizer.events.utility_functions import fetch_user_items, generate_active_user_select_field,\
    is_event_active, is_user_active, return_qty_price_select_field
from groupbuyorganizer.events.utility_objects import BreakdownObject, CaseSplitItemGroup, EventItem, \
    MyOrderObject, SummaryObject,  StructuredEventItemList, UserTotalItem


events = Blueprint('events', __name__)

@events.route('/events/<int:event_id>/items/', methods=['GET', 'POST'])
@events.route('/events/<int:event_id>/', methods=['GET', 'POST'])
@login_required
def event(event_id):

    # Item add form setup
    instance = Instance.query.first()
    event = Event.query.get_or_404(event_id)
    available_categories = Category.query.order_by('name')
    categories_list = [(piece.id, piece.name) for piece in available_categories]
    form = CreateItemForm()
    form.category_id.choices = categories_list

    # Remove user from event form
    remove_user_from_event_form = SelectUserFromEventForm()
    remove_user_from_event_form.user_to_select.choices = generate_active_user_select_field(event.id)

    #Items Setup
    items = database.session.query(Item, Category.name).filter_by(event_id=event.id).join(Category, Item.category_id
                                                            == Category.id).order_by(Category.name, Item.name).all()
    structured_item_list = None
    if items:
        structured_item_list = StructuredEventItemList(items, event_id)

    if form.validate_on_submit() and form.item_name.data:
        item = Item(name=form.item_name.data, price=form.price.data, packing=form.packing.data,
                    category_id=form.category_id.data, added_by=current_user.get_id(), event_id=event_id)
        database.session.add(item)
        database.session.commit()
        flash('Item successfully added!', 'success')
        return redirect(url_for('events.event', event_id=event_id))

    if remove_user_from_event_form.validate_on_submit():
        if current_user.is_admin == False:
            flash('Access denied', 'danger')
            return redirect(url_for('general.home'))
        active_user = User.query.filter_by(id=remove_user_from_event_form.user_to_select.data).first()
        case_buys = CaseBuy.query.filter_by(event_id=event_id, user_id=active_user.id).all()
        for case_buy in case_buys:
            database.session.delete(case_buy)
        case_piece_commits = CasePieceCommit.query.filter_by(user_id=active_user.id, event_id=event_id).all()
        case_piece_commit_ids = []
        for case_piece_commit in case_piece_commits:
            case_piece_commit_ids.append(case_piece_commit.id)
            database.session.delete(case_piece_commit)
            database.session.commit()
        affected_case_splits = database.session.query(CaseSplit).filter(CaseSplit.id.in_(case_piece_commit_ids)).all()

        # Removing case splits when user was only partipants, and changing the rest to is_complete=False if they were
        # initially marked as complete.
        for case_split in affected_case_splits:
            if not case_split.commits:
                database.session.delete(case_split)
            else:
                if case_split.is_complete == True:
                    case_split.is_complete = False
        database.session.commit()

        database.session.commit()
        flash(f'All transactions for {active_user.username} successfully removed from event!', 'info')
        return redirect(url_for('events.event', event_id=event_id))

    return render_template('event.html', event=event, form=form, title=f'{event.name} Overview',
                           structured_item_list=structured_item_list,
                           remove_user_from_event_form=remove_user_from_event_form,
                           users_can_see_master_overview=instance.users_can_see_master_overview)


@events.route('/events/<int:event_id>/edit', methods=['GET', 'POST'])
@login_required
def event_edit(event_id):
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    event = Event.query.get_or_404(event_id)
    event_name_form = CreateEventForm()
    event_edit_form = EventExtraChargeForm()
    if event_name_form.validate_on_submit():
        event.name = event_name_form.event_name.data
        database.session.commit()
        flash(f'{event.name} has been edited!', 'info')
        return redirect(url_for('events.event_edit', event_id=event_id))
    if event_edit_form.validate_on_submit():
        event.extra_charges = event_edit_form.extra_charges.data
        event.notes = event_edit_form.event_notes.data
        database.session.commit()
        flash('Extra charges updated!', 'info')
        return redirect(url_for('events.event_edit', event_id=event_id))
    elif request.method == 'GET':
        event_name_form.event_name.data = event.name
        event_edit_form.extra_charges.data = event.extra_charges
        if event.notes:
            event_edit_form.event_notes.data = event.notes

    return render_template('event_edit.html', title=f'{event.name} - Edit', event_name_form=event_name_form,
                           event_extra_charge_form=event_edit_form, event=event)


@events.route("/category_settings/<int:event_id>/remove/", methods=['GET'])
@login_required
def event_remove(event_id):
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    event = Event.query.get_or_404(event_id)
    database.session.delete(event)
    database.session.commit()
    flash('Event deleted!', 'info')
    return redirect(url_for('general.home'))


@events.route("/category_settings/<int:event_id>/lock/", methods=['GET'])
@login_required
def event_lock(event_id):
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    event = Event.query.get_or_404(event_id)
    event.is_locked = True
    database.session.commit()
    flash('Event locked!', 'info')
    return redirect(url_for('events.event_edit', event_id=event_id))


@events.route("/category_settings/<int:event_id>/unlock/", methods=['GET'])
@login_required
def event_unlock(event_id):
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    event = Event.query.get_or_404(event_id)
    event.is_locked = False
    database.session.commit()
    flash('Event unlocked!', 'info')
    return redirect(url_for('events.event_edit', event_id=event_id))


@events.route("/category_settings/<int:event_id>/close/", methods=['GET'])
@login_required
def event_close(event_id):
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    event = Event.query.get_or_404(event_id)
    event.is_locked = True
    event.is_closed = True
    database.session.commit()
    flash('Event closed!', 'info')
    return redirect(url_for('events.event_edit', event_id=event_id))


@events.route("/category_settings/<int:event_id>/open/", methods=['GET'])
@login_required
def event_open(event_id):
    if current_user.is_admin == False:
        flash('Access denied', 'danger')
        return redirect(url_for('general.home'))
    event = Event.query.get_or_404(event_id)
    event.is_closed = False
    database.session.commit()
    flash('Event opened!', 'info')
    return redirect(url_for('events.event_edit', event_id=event_id))


@events.route('/events/<int:event_id>/items/<int:item_id>/', methods=['GET', 'POST'])
@login_required
def item(event_id, item_id):
    event = Event.query.get_or_404(event_id)
    item = Item.query.get_or_404(item_id)

    # Item edit form
    available_categories = Category.query.order_by('name')
    categories_list = [(piece.id, piece.name) for piece in available_categories]
    edit_item_form = EditItemForm()
    edit_item_form.category_id.choices = categories_list

    # Added by name
    added_by_user = User.query.filter_by(id=item.added_by).first()

    # Case Quantity Form
    order_case_form = CaseQuantityOrderForm()
    order_case_form.quantity.choices = return_qty_price_select_field(100, item.price, item.packing,
                                                                     whole_cases=True)

    # Create Case Splits
    create_case_split_form = CreateCaseSplitForm()
    create_case_split_form.piece_quantity.choices = \
        return_qty_price_select_field(item.packing - 1, item.price, item.packing)

    # Customized item/order view
    event_item = EventItem(item, event_id)

    if edit_item_form.validate_on_submit():
        item.name = edit_item_form.item_name.data
        item.category_id = edit_item_form.category_id.data
        item.price = edit_item_form.price.data
        additional_flash_message = ""
        if item.packing != edit_item_form.packing.data:
            additional_flash_message = 'Because of the change in item packing, all case splits have been removed.'
            case_splits = CaseSplit.query.filter_by(item_id=item.id)
            for case_split in case_splits:
                database.session.delete(case_split)
        item.packing = edit_item_form.packing.data
        database.session.commit()
        flash(f'Item successfully edited!  {additional_flash_message}', 'info')

groupbuyorganizer/templates/account.html
{% extends "primary.html" %}
{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="{{ url_for('general.home') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Account</li>

        </ol>
    </nav>
    <div class="container">
        <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    </div>
{% endblock content %}

groupbuyorganizer/templates/event_edit.html
{% extends "primary.html" %}
{% block content %}
    <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item" aria-current="page"><a href="{{ url_for('general.home') }}">Home</a></li>
                <li class="breadcrumb-item" aria-current="page"><a href="{{ url_for('events.event', event_id=event.id) }}">{{ event.name }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit</li>
            </ol>
    </nav>
    <div class="alert alert-info mx-auto">
        <p>This is an admin-only area where you can make changes to the event.  Feel free to make a test event and mess
        around with it to become more comfortable with the app.</p>
        <p class="font-weight-bold">Event notes:</p>
        <p>This is a text field that appears on the top of the event page as a colored
        alert, visible to all users.  You can use this to post inportant information about the group buy, deadlines, etc.</p>
        <p class="font-weight-bold">Added charges:</p>
        <p>If you have any associated charges with the group buy to be distributed
        amongst the active group buy users, this is where you add it.  One such example could be the shipping cost, gas
        cost of transporting, etc.  It will distribute the cost amongst users proportionally to the size of their order,
        so smaller orders will pay less while larger ones pay more.  Lets say the total order is $1000, your added
        charges total to $100, and a given user's total is $150.  Since his order is 15% the total cost of the group
        buy, he will pay for 15% of that added fee, which comes out to $15.</p>
        <p class="font-weight-bold">Locking event:</p>
        <p>This will lock in all current case orders and case splits, and prevent any additions, changes
        or deletions.  Adding new items will be restricted as well.  If you unlock it, changes from the users will be
        allowed again.  Use this if you're wrapping up the event, or otherwise are encountering any problems.</p>
        <p class="font-weight-bold">Closing event:</p>
        <p>This is simply a way to show the userbase that an event has officially concluded.  Just like
        locking an event, nothing can be changed.</p>
        <p class="font-weight-bold">Deleting event:</p>
        <p>As it states, the event gets removed.  All items, case buys, and case splits get removed as
        well.  Categories remain unaffected.  Please be aware that this is a permanent action.  Once its gone, its gone!</p>
    </div>
    <div class="container mt-5">
        <form method="POST" action="">
            {{ event_name_form.hidden_tag() }}
            <div class="form-group">
                <label>Event Name</label>
                {% if event_name_form.event_name.errors %}
                        {{ event_name_form.event_name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in event_name_form.event_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ event_name_form.event_name(class="form-control form-control-lg") }}
                    {% endif %}
            </div>
            <div class="form-group">
                {{ event_name_form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <h3 class="container mt-5 border-bottom">Event Notes</h3>
    <form method="POST" action="">
    <div class="container">
            <div class="form-group">
                {{ event_extra_charge_form.event_notes(class="form-control textarea") }}
            </div>
    </div>
    <h3 class="container mt-5 border-bottom">Event Configuration</h3>
    <div class="container">
        <table class="table mt-3">
                            <thead>
                            <tr>
                                <th scope="col">Added Charges ($)</th>
                                <th scope="col">Toggle Lock?</th>
                                <th scope="col">Close Group Buy?</th>
                            </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                            {{ event_extra_charge_form.hidden_tag() }}
                                            {% if event_extra_charge_form.extra_charges.errors %}
                                                {{ event_extra_charge_form.extra_charges(class="form-control form-control is-invalid float-left") }}
                                                <div class="invalid-feedback">
                                                {% for error in event_extra_charge_form.extra_charges.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                                </div>
                                            {% else %}
                                                {{ event_extra_charge_form.extra_charges(class="form-control form-control float-left") }}
                                            {% endif %}
                                            {{ event_extra_charge_form.submit(class="btn btn-outline-info float-right ml-2") }}
                                    </td>
                                    {% if event.is_closed %}
                                        <td><a class="btn btn-outline-success disabled" href="#" role="button">Unlock</a></td>
                                        <td><a class="btn btn-outline-secondary" href="{{ url_for('events.event_open', event_id=event.id) }}" role="button">Open</a></td>
                                    {% else %}
                                        {% if event.is_locked%}
                                            <td><a class="btn btn-outline-success" href="{{ url_for('events.event_unlock', event_id=event.id) }}" role="button">Unlock</a></td>
                                            <td><a class="btn btn-outline-secondary" href="{{ url_for('events.event_close', event_id=event.id) }}" role="button">Close</a></td>
                                        {% else %}
                                            <td><a class="btn btn-outline-warning" href="{{ url_for('events.event_lock', event_id=event.id) }}" role="button">Lock</a></td>
                                            <td><a class="btn btn-outline-secondary" href="{{ url_for('events.event_close', event_id=event.id) }}" role="button">Close</a></td>
                                        {% endif %}
                                    {% endif %}
                                </tr>
                            </tbody>
                        </table>
    </div>
    </form>
    <h3 class="container mt-5 border-bottom">Danger Zone</h3>
    <div class="container">
        <button type="button" class="btn btn-outline-danger mb-5 mt-1" data-toggle="modal" data-target="#warningModal">
            Delete Event
        </button>
    </div>

    <div class="modal fade" id="warningModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete Event?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you wish to delete this event?  This cannot be undone!
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-outline-danger" href="{{ url_for('events.event_remove', event_id=event.id) }}" role="button">Delete</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

groupbuyorganizer/templates/test_pdf.html
{% extends "primary.html" %}

{% set is_pdf = true %}

{% block content %}
    <div class="alert alert-success mx-auto" role="alert">
        <h1>Success!</h1>
    </div>
{% endblock content %}

groupbuyorganizer/templates/user_settings.html
{% extends "primary.html" %}
{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="{{ url_for('general.home') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Admin</li>
            <li class="breadcrumb-item active" aria-current="page">User Settings</li>
        </ol>
    </nav>
    <div class="container mt-5">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">User Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Date Registered</th>
                    <th scope="col">Account Level</th>
                    <th scope="col">Toggle Admin</th>
                    <th scope="col">Disable Account</th>
                </tr>
            </thead>
            <tbody>
            {% for user in users %}
                {% if user.is_admin %}
                    <tr class="table-success">
                {% elif user.disabled %}
                    <tr class="table-warning">
                {% else %}
                    <tr>
                {% endif %}
                <th scope="row">{{ user.username }}</th>
                <td>{{ user.email }}</td>
                <td>{{ user.date_created }}</td>
                {% if user.is_root %}
                    <td>Root Admin</td>
                {% elif user.is_admin %}
                    <td>Admin</td>
                {% elif user.disabled %}
                    <td>Disabled</td>
                {% else %}
                    <td>User</td>
                {% endif %}

                {% if user.disabled %}
                    <td><a class="btn btn-outline-success btn-sm disabled" href="#" role="button">Promote</a></td>
                {% else %}
                    {% if not user.is_admin and current_user.is_root %}
                        <td><a class="btn btn-outline-success btn-sm" href="{{ url_for('admin.promote_user', user_id=user.id) }}" role="button">Promote</a></td>
                    {% elif user.is_admin and current_user.is_root %}
                        {% if user.is_root %}
                            <td><a class="btn btn-outline-warning btn-sm disabled" href="#" role="button">Demote</a>
                        {% else %}
                            <td><a class="btn btn-outline-warning btn-sm" href="{{ url_for('admin.demote_user', user_id=user.id) }}" role="button">Demote</a></td>
                        {% endif %}
                    {% elif not user.is_admin and not current_user.is_root %}
                        <td><a class="btn btn-outline-success btn-sm disabled" href="#" role="button">Promote</a></td>
                    {% elif user.is_admin and not current_user.is_root %}
                        <td><a class="btn btn-outline-warning btn-sm disabled" href="#" role="button">Demote</a></td>
                    {% endif %}
                {% endif %}

                {% if not user.disabled %}
                    {% if user.is_root or user.is_admin and current_user.is_admin and not current_user.is_root %}
                        <td><a class="btn btn-outline-danger btn-sm disabled" href="#" role="button">Disable</a></td>
                    {% else %}
                        <td><a class="btn btn-outline-danger btn-sm" href="{{ url_for('admin.disable_user', user_id=user.id) }}" role="button">Disable</a></td>
                    {% endif %}
                {% else %}
                    <td><a class="btn btn-outline-success btn-sm" href="{{ url_for('admin.enable_user', user_id=user.id) }}" role="button">Enable</a></td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}